# Generated by Django 6.0.6 on 2026-10-01 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scans', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scan',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('complete', 'Complete'), ('failed', 'Failed'), ('interrupted', 'Interrupted')], default='pending', max_length=20),
        ),
    ]
